name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

    - name: Copy code to VM
      run: |
        scp -i ~/.ssh/id_rsa -r . perf@${{ secrets.VM_HOST }}:/home/perf/my-python-app

    - name: Restart App on VM
      run: |
        ssh -i ~/.ssh/id_rsa perf@${{ secrets.VM_HOST }} << EOF
          cd /home/perf/my-python-app
          docker-compose down
          docker-compose up -d --build
        EOF
